
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport-service
  namespace: nginx-mesh
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: nginx-mesh
spec:
  type: NodePort
  ports:
  - name: port30000
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: nginx-mesh